### ISSUE TITLE
Save to local storage

### ISSUE THREAD

**Issue by Louboutin1017** [jillix/piklor.js#13]
Is it possible to save the selected colors to local storage?

I mean, when the users chooses yellow the header should remain yellow on page refresh or on the next visit.

Kindly advise,
thanks

**Comment by IonicaBizau** [comment]
Use `colorChosen` to save the color in `localStorage` and then the [`set`](https://github.com/jillix/piklor.js#setc-p) method to set the color from `localStorage`.

Cheers!
