### ISSUE TITLE
Callback function on color choice

### ISSUE THREAD

**Issue by villanus** [jillix/piklor.js#6]
It would be nice to be able to run a function on change.  In case we need to do more than color a div

**Comment by IonicaBizau** [comment]
Hi @villanus! Use the [`colorChosen`](https://github.com/jillix/piklor.js#colorchosencb) method to append new color choice callbacks. Call it multiple times if you want to append multiple functions. 

Hope this helps. If you have any other questions, let me know. :four_leaf_clover:

**Comment by villanus** [comment]
thanks

**Comment by IonicaBizau** [comment]
@villanus You're welcome! :+1:

**Comment by villanus** [comment]
i noticed you are also very active on svg.js.
are these two libraries meant to play well with each other?

**Comment by IonicaBizau** [comment]
@villanus This library uses DOM HTML elements, but depending on what you have, it should work with SVG too: for example, the color picker could be in one corner of the page and there you select a color for an svg element. Once the color is selected, the svg element background color can be updated. 

We actually use this setup internally at jillix. :grin:

**Comment by villanus** [comment]
Just translated jillix to english to understand what you guys are up to =)

Its a really cool color picker.   We are hoping to use it in a way where change the class on different svg elements.   Trying to build a custom product builder (for printing) using SVG.js, and investigating color pallete pickers.    By far this is the nicest.  

One of our requirements is to make the picker appear full screen on phones.   The CSS on this is so clean that I can do that in just a few lines.   Really Really Nice.

**Comment by IonicaBizau** [comment]
@villanus `jillix` is not really translatable—`jillix` is `jillix`. :joy: In fact, it's based on some initial letters of two names.

> The CSS on this is so clean that I can do that in just a few lines. Really Really Nice.

Glad to hear that! Yes, the CSS is 100% customizable. :sparkles:

**Comment by villanus** [comment]
I meant I translated the site =)
Your git profile / stackoverflow profile is very amazing!

Thanks again for the amazing work!

**Comment by IonicaBizau** [comment]
@villanus You're welcome! Glad you like my SO and GH profiles. Maybe you find some interesting stuff there. :smile: Thanks for following me!
