### ISSUE TITLE
Is there a way to open color selector in bootstrap modal?

### ISSUE THREAD

**Issue by WriterStat** [jillix/piklor.js#7]
I like the simplicity of this.

I have multiple bootstrap panels and I'd like to open 1 piklor color picker inside a bootstrap modal to change their individual colors.

Is there a way to easily open color selector in bootstrap modal instead of a div? Or is there a way to auto open piklor found/placed inside a bootstrap modal for color selection?

Example: panel A has a fontawesome color icon, I click it and it opens a bootstrap modal passing a handle from Panel A to the bootstrap modal. Inside the opened modal is an open piklor color selector ready to be used. I click on piklor and panel A's top changes color.

I can create the icon click/modal open event and the modal etc... Just wondering if there's an easy way to have piklor open and ready inside a bootstrap modal?

javascript is not my native tongue. =)

Thanks!

Apologize if I didn't word this correctly. And I didn't want to deconstruct your code. =)

**Comment by WriterStat** [comment]
It looks like I could place a piklor color picker inside a bootstrap modal by setting 'autoclose' to false and by setting 'closeOnBlur' to false.

And by ignoring the 'open' and 'openEvent'.

Then I could use the pk.colorChosen function to change the panel top color as well as save the color to the database using ajax.

Does this sound right? Thx!

**Comment by IonicaBizau** [comment]
You can even override the `close` and `open` functions:
```js
var pk = new Piklor(".color-picker", [...])
pk.close = function () {
  this.elm.style.display = "none"; // Instead of this, close your modal
  this.isOpen = false;
};

pk.open = function () {
  this.elm.style.display = this.options.style.display; // Instead of this open your modal
  this.isOpen = true;
};
```

Is that what you want?
